### ISSUE TITLE
RTL_433 to MQTT Bridge does not start

### ISSUE THREAD

**Issue by Try2Fly** [james-fry/hassio-addons#16]
Hi, I've had the great addon working in the past. But since a fresh installation I cannot get the addon started. The log section in the addon stays empty.

This the only message in the log of hassio:

> 18-07-20 11:09:56 INFO (SyncWorker_7) [hassio.docker.addon] Start docker addon f3248fb7/aarch64-addon-rtl4332mqtt with version 0.2
> 18-07-20 11:13:34 INFO (SyncWorker_7) [hassio.docker.interface] Clean f3248fb7/aarch64-addon-rtl4332mqtt docker application
> 18-07-20 11:13:36 INFO (SyncWorker_7) [hassio.docker.addon] Start docker addon f3248fb7/aarch64-addon-rtl4332mqtt with version 0.2

**Comment by Try2Fly** [comment]
Update:
since update to HA 0.74 I'm getting the following in the log:

> Starting RTL_433 with parameters:
> MQTT Host = http://192.168.1.202
> MQTT User = XXXXXXXXXX
> MQTT Password = XXXXXXXXX
> MQTT Topic = homeassistant/sensor/bbq
> RTL_433 Protocol = 71
> RTL_433 Frequency = 433920000
> RTL_433 Gain = 0
> RTL_433 Frequency Offset = 0
> + /usr/local/bin/rtl_433 -F json -R 71 -f 433920000 -g 0 -p 0
> + read line
> Registering protocol [71] "Maverick ET-732/733 BBQ Sensor"
> Registered 1 out of 103 device decoding protocols
> Found 1 device(s)
> trying device  0:  Realtek, RTL2838UHIDIR, SN: 00000001
> Found Rafael Micro R820T tuner
> Using device 0: Generic RTL2832U OEM
> Exact sample rate is: 250000.000414 Hz
> [R82XX] PLL not locked!
> Sample rate set to 250000.
> Bit detection level set to 0 (Auto).
> Tuner gain set to Auto.
> Reading samples in async mode...
> Tuned to 433.920MHz.
> Allocating 15 zero-copy buffers
> Bus error (core dumped)

**Comment by Try2Fly** [comment]
update 2:

Installed HASSOS for 32bit and now get the following error:

Unable to connect (Lookup error.).

**Comment by messismore** [comment]
Looks like you’re almost there. RTL can’t find the MQTT host though. Delete the ‘http:’ in front of the IP and it should work.

**Comment by Try2Fly** [comment]
wow thanks! That was the last bit indeed. I've changed the settings many time, looks like I didn't try this after on Hassos 32bit.

Thanks alot!
