### ISSUE TITLE
Addon won't start

### ISSUE THREAD

**Issue by sdrasmussen** [james-fry/hassio-addons#18]
I have what is probably a simple problem, but no idea what do do about it.  When I try to start the addon, I get the following message in the logs:

/bin/sh: /rtl2mqtt.sh: not found

I did copy rtl2mqtt.sh to the directory config/rtl4332mqtt as the directions specify, but no joy.  Any idea how to figure out what I did wrong?

**Comment by messismore** [comment]
Hm that's strange. Any chance your file browser added a hidden file extension to your .sh file?

**Comment by sdrasmussen** [comment]
well, that would be a neat trick, for a browser to add an extension to a
file from a CLI...so, the answer is no.

**Comment by sdrasmussen** [comment]
Oh almost forgot...another guy on Discord, cogneato, installed it and gets
the same exact error.

**Comment by davtes77** [comment]
Hi,
I experienced the same issue using a rtl2mqtt.sh file created on a windows 10 PC and then uploaded via samba share.
Solved downloading the rtl2mqtt.sh file directly on hassio (using an ssh session) with:

`wget https://raw.githubusercontent.com/james-fry/hassio-addons/master/rtl4332mqtt/rtl2mqtt.sh`

Hope this help you!

**Comment by Alessandro1981** [comment]
Hello, I am getting the following errors (see the last 6 rows of the attached log).
 
> Starting RTL_433 with parameters:
> MQTT Host = hassio.local
> MQTT User =
> MQTT Password =
> MQTT Topic = homeassistant/sensor/currentcost
> RTL_433 Protocol = 32
> RTL_433 Frequency = 319500000
> RTL_433 Gain = 60
> RTL_433 Frequency Offset = 350
> Registering protocol [1] "Fine Offset Electronics WH1080/WH3080 Weather Station"
> Registered 1 out of 101 device decoding protocols
> Found 1 device(s)
> trying device  0:  Realtek, RTL2838UHIDIR, SN: 00000001
> Detached kernel driver
> Found Rafael Micro R820T tuner
> Using device 0: Generic RTL2832U OEM
> Exact sample rate is: 250000.000414 Hz
> [R82XX] PLL not locked!
> Sample rate set to 250000.
> Bit detection level set to 0 (Auto).
> Tuner gain set to 60.000000 dB.
> Reading samples in async mode...
> Tuned to 319500000 Hz.
> Allocating 15 zero-copy buffers
> Failed to allocate zero-copy buffer for transfer 0
> Falling back to buffers in userspace
> cb transfer status: 1, canceling...
> WARNING: async read failed (-5).
> Library error -5, exiting...
> Reattaching kernel driver failed!

I am not understanding how to fix it...someone can help me?
Alessandro

**Comment by james-fry** [comment]
@davtes77 has it correct.
I recently needed to reinstall the addon and I needed to create the file via ssh. 
Even creating it via the VS code (editor) HASSIO addon didnt work.

**Comment by james-fry** [comment]
I have no idea why copying the script via samba does not work but creating via scp or direct on hassio via editor does work.
As a workaround I added info to the repo readme.

**Comment by sircompo** [comment]
I just experienced this and figured out the file was saved with CRLF (MSDOS) encoding.
Once the extraneous carriage returns had been removed, it worked fine.

To test for this, use the home assistant terminal and try running the script; you'll get a 'bad interpreter' warning.

_(yeah, I know this is an old and closed issue, but I figured if I ended up here looking for a solution, others might also)_
